### ISSUE TITLE
Error running InstallQS.sh

### ISSUE THREAD

**Issue by julisanchez** [Bedework/bedework#135]
Running ./installQS.sh I got these errors and can't access port 8080.
On port 8082 I get "Sorry, remote connections ('webAllowOthers') are disabled on this server."
I was following the steps in section 4.1 of https://bedework.github.io/bedework/#_calendar_architecture

```
[info] *********************************************Loading properties from /home/juli/bw-3.13.2/quickstart-dev/bedework/config/wildfly.deploy.properties
java.lang.Exception: /home/juli/bw-3.13.2/quickstart-dev/bedework/config/wildfly.deploy.properties must exist and be a file
	at org.bedework.util.deployment.Utils.file(Utils.java:181)
	at org.bedework.util.deployment.Process.loadProperties(Process.java:107)
	at org.bedework.util.deployment.Process.execute(Process.java:207)
	at org.bedework.util.maven.deploy.DeployEars.execute(DeployEars.java:88)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)


[INFO] --- maven-source-plugin:2.1.2:test-jar (attach-sources) @ bw-calendar-engine-caldav ---
[INFO] No sources in project. Archive not created.

[INFO] ------------------------------------------------------------------------
cd /home/juli/bw-3.13.2/quickstart-3.13.2/bw-cli
mvn -P bedework-3 -Dmaven.test.skip=true install
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

---------------------------------------------------------------
Index data
About to start h2 process
rm: cannot remove '/home/juli/bw-3.13.2/quickstart-3.13.2/wildfly/standalone/tmp/h2.pid': No such file or directory
About to start ES docker image
rm: cannot remove '/home/juli/bw-3.13.2/quickstart-3.13.2/wildfly/standalone/tmp/es.cid': No such file or directory
./bedework/build/quickstart/linux/startES.sh: line 30: docker: command not found
pidfile=/home/juli/bw-3.13.2/quickstart-3.13.2/wildfly/standalone/tmp/bedework.jboss.pid
./wildfly/bin/standalone.sh -b 0.0.0.0 -Dhawtio.authenticationEnabled=true -Dhawtio.realm=other -Dhawtio.role=hawtioadmin -Dorg.bedework.log.level=INFO -Dorg.bedework.loglevel.exprfilters=INFO -Dorg.bedework.config.dir=/home/juli/bw-3.13.2/quickstart-3.13.2/wildfly/standalone/configuration/bedework/ -Dorg.bedework.config.pfile=/home/juli/bw-3.13.2/quickstart-3.13.2/wildfly/standalone/configuration/bedework/config.defs -Dorg.bedework.data.dir=/home/juli/bw-3.13.2/quickstart-3.13.2/wildfly/standalone/data/bedework/ -Dorg.bedework.carddav.datauri=/home/juli/bw-3.13.2/quickstart-3.13.2/wildfly/standalone/data/bedework/carddavConfig/ -Dorg.bedework.synch.datauri=/home/juli/bw-3.13.2/quickstart-3.13.2/wildfly/standalone/data/bedework/synch/
./bedework/build/quickstart/linux/startwildfly.sh: line 215: ./wildfly/bin/standalone.sh: No such file or directory
TCP server running at tcp://192.168.0.17:40825 (only local connections)
The Web Console server could not be started. Possible cause: another server is already running at http://192.168.0.17:8082
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Exception opening port "8082" (port may be in use), cause: "java.net.BindException: Address already in use (Bind failed)" [90061-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:180)
	at org.h2.util.NetUtils.createServerSocket(NetUtils.java:146)
	at org.h2.server.web.WebServer.start(WebServer.java:340)
	at org.h2.tools.Server.start(Server.java:482)
	at org.h2.tools.Server.runTool(Server.java:321)
	at org.h2.tools.Server.main(Server.java:118)

Caused by: java.net.BindException: Address already in use (Bind failed)
	at java.base/java.net.PlainSocketImpl.socketBind(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:436)
	at java.base/java.net.ServerSocket.bind(ServerSocket.java:395)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:257)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:149)
	at org.h2.util.NetUtils.createServerSocketTry(NetUtils.java:176)
	... 5 more

--2020-06-08 17:07:31--  http://localhost:8080/cal
Resolving localhost (localhost)... 127.0.0.1
Connecting to localhost (localhost)|127.0.0.1|:8080... failed: Connection refused.
cmd:org.jolokia.client.exception.J4pConnectException: Cannot connect to http://localhost:8080/hawtio/jolokia: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at org.jolokia.client.J4pClient.mapException(J4pClient.java:325)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:198)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:168)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:117)
	at org.bedework.util.jolokia.JolokiaClient.execute(JolokiaClient.java:155)
	at org.bedework.bwcli.JolokiaConfigClient.rebuildIndexes(JolokiaConfigClient.java:85)
	at org.bedework.bwcli.jmxcmd.CmdRebuildIdx.doExecute(CmdRebuildIdx.java:20)
	at org.bedework.bwcli.jmxcmd.JmxCmd.execute(JmxCmd.java:33)
	at org.bedework.util.cli.Cli.processCmds(Cli.java:124)
	at org.bedework.bwcli.BwCli.main(BwCli.java:220)

Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:190)
	... 8 more

Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
	... 19 more

cmd:org.jolokia.client.exception.J4pConnectException: Cannot connect to http://localhost:8080/hawtio/jolokia: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at org.jolokia.client.J4pClient.mapException(J4pClient.java:325)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:198)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:168)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:117)
	at org.bedework.util.jolokia.JolokiaClient.execString(JolokiaClient.java:130)
	at org.bedework.bwcli.JolokiaConfigClient.makeAllIdxProd(JolokiaConfigClient.java:133)
	at org.bedework.bwcli.jmxcmd.CmdMakeIdxProd.doExecute(CmdMakeIdxProd.java:21)
	at org.bedework.bwcli.jmxcmd.JmxCmd.execute(JmxCmd.java:33)
	at org.bedework.util.cli.Cli.processCmds(Cli.java:124)
	at org.bedework.bwcli.BwCli.main(BwCli.java:220)

Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:190)
	... 8 more

Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
	... 19 more

cmd:org.jolokia.client.exception.J4pConnectException: Cannot connect to http://localhost:8080/hawtio/jolokia: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at org.jolokia.client.J4pClient.mapException(J4pClient.java:325)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:198)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:168)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:117)
	at org.bedework.util.jolokia.JolokiaClient.execString(JolokiaClient.java:130)
	at org.bedework.bwcli.JolokiaConfigClient.listIndexes(JolokiaConfigClient.java:73)
	at org.bedework.bwcli.jmxcmd.CmdListIdx.doExecute(CmdListIdx.java:17)
	at org.bedework.bwcli.jmxcmd.JmxCmd.execute(JmxCmd.java:33)
	at org.bedework.util.cli.Cli.processCmds(Cli.java:124)
	at org.bedework.bwcli.BwCli.main(BwCli.java:220)

Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:8080 [localhost/127.0.0.1] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:140)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:314)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:186)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:57)
	at org.jolokia.client.J4pClient.execute(J4pClient.java:190)
	... 8 more

Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:72)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:117)
	... 19 more
     └─1880 -bash
```

**Comment by douglm** [comment]
It looks like you are trying the dev version which spends most of it's 
life broken to some extent. I'd suggest cleaning everything out - 
ensuring no h2 or apacheds processes are running and try again with the 
latest release.

Recent experience suggests it's actually easier to install elasticsearch 
yourself. Running the docker image requires you to install docker etc.

Take a look at

https://bedework.github.io/bedework/#installing-bedwork
