### ISSUE TITLE
Error while trying to run quickstart shell script.

### ISSUE THREAD

**Issue by depava95** [Bedework/bedework#140]
When I try to run [installQS.sh](https://github.com/Bedework/bedework/blob/master/build/quickstart/linux/installQS.sh) I have an exception. 
**Mac OS  Mojave**
```
TCP server running at tcp://192.168.31.52:9092 (only local connections)
Web Console server running at http://192.168.31.52:8082 (only local connections)
21:07:47,177 INFO  [org.jboss.modules] (main) JBoss Modules version 1.10.2.Final
21:07:52,807 INFO  [org.jboss.msc] (main) JBoss MSC version 1.4.12.Final
21:07:52,820 INFO  [org.jboss.threads] (main) JBoss Threads version 2.4.0.Final
21:07:52,995 INFO  [org.jboss.as] (MSC service thread 1-2) WFLYSRV0049: WildFly Full 21.0.0.Final (WildFly Core 13.0.1.Final) starting
21:07:53,665 WARN  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0456: System property "hawtio.realm" is already set in the <system-properties> section of the configuration file. The value set in the command line will be overridden by that value.
21:07:53,666 WARN  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0456: System property "hawtio.role" is already set in the <system-properties> section of the configuration file. The value set in the command line will be overridden by that value.
21:07:54,026 INFO  [org.jboss.as.controller] (Controller Boot Thread) OPVDX003: No schemas available from /Users/biedin/Documents/ubuntu/latest/quickstart-3.13.2/wildfly/docs/schema - disabling validation error pretty printing
21:07:54,053 ERROR [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0055: Caught exception during boot: org.jboss.as.controller.persistence.ConfigurationPersistenceException: WFLYCTL0085: Failed to parse configuration
	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:143)
	at org.jboss.as.server.ServerService.boot(ServerService.java:395)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:416)
	at java.base/java.lang.Thread.run(Thread.java:836)
Caused by: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module org.jboss.as.security
	at org.jboss.as.controller.parsing.DeferredExtensionContext.load(DeferredExtensionContext.java:100)
	at org.jboss.as.server.parsing.StandaloneXml_10.readServerElement(StandaloneXml_10.java:219)
	at org.jboss.as.server.parsing.StandaloneXml_10.readElement(StandaloneXml_10.java:119)
	at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:126)
	at org.jboss.as.server.parsing.StandaloneXml.readElement(StandaloneXml.java:52)
	at org.jboss.staxmapper.XMLMapperImpl.processNested(XMLMapperImpl.java:122)
	at org.jboss.staxmapper.XMLMapperImpl.parseDocument(XMLMapperImpl.java:76)
	at org.jboss.as.controller.persistence.XmlConfigurationPersister.load(XmlConfigurationPersister.java:126)
	... 3 more
Caused by: java.util.concurrent.ExecutionException: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at org.jboss.as.controller.parsing.DeferredExtensionContext.load(DeferredExtensionContext.java:92)
	... 10 more
Caused by: javax.xml.stream.XMLStreamException: WFLYCTL0083: Failed to load module
	at org.jboss.as.controller.parsing.DeferredExtensionContext.loadModule(DeferredExtensionContext.java:129)
	at org.jboss.as.controller.parsing.DeferredExtensionContext.access$000(DeferredExtensionContext.java:44)
	at org.jboss.as.controller.parsing.DeferredExtensionContext$1.call(DeferredExtensionContext.java:74)
	at org.jboss.as.controller.parsing.DeferredExtensionContext$1.call(DeferredExtensionContext.java:71)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1348)
	at java.base/java.lang.Thread.run(Thread.java:836)
	at org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: org.jboss.modules.ModuleNotFoundException: org.jboss.as.security
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:297)
	at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:283)
	at org.jboss.as.controller.parsing.DeferredExtensionContext.loadModule(DeferredExtensionContext.java:111)
	... 10 more

21:07:54,080 FATAL [org.jboss.as.server] (Controller Boot Thread) WFLYSRV0056: Server boot has failed in an unrecoverable manner; exiting. See previous messages for details.
21:07:54,229 INFO  [org.jboss.as] (MSC service thread 1-8) WFLYSRV0050: WildFly Full 21.0.0.Final (WildFly Core 13.0.1.Final) stopped in 122ms
17288
--2020-11-17 21:08:15--  http://localhost:8080/cal
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8080... failed: Connection refused.
run.sh: line 1020: ./client: No such file or directory
```

**Comment by douglm** [comment]
Which version are you trying to deploy?

The latest is 3.13.2 which needs to be installed with the script at

https://github.com/Bedework/bedework/raw/bedework-3.13.2/build/quickstart/linux/installQS.sh

It looks like you tried the dev script which installs a later wildfly.

I'm hoping to release a new version in a couple of weeks

**Comment by depava95** [comment]
Thank you for the quick response! I have tried **3.13.2** and have another exception. (before that snippet of exception everything went well)
I can deploy Bedework **3.10** but I doubt how relevant it is.
There are many significant changes since the **3.10** version?  


```
cd /Users/biedin/Documents/ubuntu/problem/quickstart-3.13.2/bw-calendar-xsl
./bedework/build/quickstart/linux/bw.sh: line 126: cd: /Users/biedin/Documents/ubuntu/problem/quickstart-3.13.2/bw-calendar-xsl: No such file or directory
mvn -P bedework-3 -Dmaven.test.skip=true install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.083 s
[INFO] Finished at: 2020-11-18T10:20:16+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/Users/biedin/Documents/ubuntu/problem/quickstart-3.13.2). Please verify you invoked Maven from the correct directory. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException
Maven build unsuccessful
---------------------------------------------------------------
update wildfly
---------------------------------------------------------------
```

```
10:20:38,129 INFO  [org.jboss.as] (Controller Boot Thread) WFLYSRV0025: WildFly Full 17.0.1.Final (WildFly Core 9.0.2.Final) started in 19640ms - Started 410 of 424 services (104 services are lazy, passive or on-demand)
--2020-11-18 10:20:47--  http://localhost:8080/cal
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-11-18 10:20:47 ERROR 404: Not Found.
```

**Comment by douglm** [comment]
Could you delete it all - try again and log the entire run - and if you 
get the same result send me the log.

It appears the cloning of the projects didn't work as bw-calendar-xsl 
doesn't exist.

I'm assuming there's an earlier error
